buildscript {
    repositories {
        maven { url = "https://cleanroommc.com" }
        maven { url = "https://maven.minecraftforge.net/" }
        mavenCentral()
    }
    dependencies {
        classpath 'net.minecraftforge.gradle:ForgeGradle:2.3-patched'
    }
}
apply plugin: 'net.minecraftforge.gradle.forge'

version = "1.0"
group = "com.example.custompaintings"
archivesBaseName = "custompaintings"

minecraft {
    version = "1.12.2-14.23.5.2860"
    runDir = "run"
    mappings = "stable_39"
    makeObfSourceJar = false
}

repositories {
    mavenCentral()
    maven { url = "https://cleanroommc.com" }
}
